#
# ==== General info ====
#
# * After editing of this file you need to check server logs to be
# sure that no errors was appeared.
#

#
# Show debug info. Possible values: true | false (default = false)
#
# This option can affect the performance.
#
debug: false

#
# Enable main features. Possible values: true | false (default = false)
#
enabled: true

#
# worlds:  ### A list of worlds.
#          ### By default, entities of all worlds will be processed.
#   - <world1>
#     ...
#   - <worldN>
#

#
# exclude-biomes:  ### A list of biomes, where the plugin doesn't work.
#                  ### List of all possible values:
#                  ### https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html
#                  ###
#                  ### By default, entities of all biomes will be processed.
#   - <biome1>
#     ...
#   - <biomeN>
#